### ISSUE TITLE
organize fa14 files

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/fieldnotes-content#10]
fa14 did not follow the wiki structure that the was established in the semesters that followed. Thus, most files are "loose" within the larger fa14/ folder.

Organize these into the three fieldnote types: 1) fieldnotes, 2) annotations, 3) profiles
Identify any that do not fit into these types and deal with them in the same way as similar files in cu-mkp/fieldnotes-restructuring#21 (likely, move them into a segregated S3 bucket)

**Comment by gschare** [comment]
The actions without `?` have been performed (see #12). Now just waiting on direction for the last few loose files.

**Comment by njr2128** [comment]
Thanks, Greg.

Outstanding: review of `?` files by PHS, then move/rename them according to her input

**Comment by njr2128** [comment]
@gschare - can you name everything properly? Once this is done, all semesters have been organized properly

**Comment by njr2128** [comment]
done!
