### ISSUE TITLE
solutions to minimize file path length

### ISSUE THREAD

**Issue by gschare** [cu-mkp/fieldnotes-content#17]
Our lowest common denominator for file path length is Windows, which enforces 256 characters max full path length.
E.g., on my machine, I installed the repo at: `/mnt/c/code/github/fieldnotes-content/`, which is `39` characters (including the trailing slash). So we have at most `217` characters left to work with, and that is assuming everyone clones their repo into a folder path as brief as mine. For safety, let's say we will allow maximum `200` more characters for path names inside the repo.

The longest paths will obviously be the deeply nested fieldnotes and annotations, which *typically* go something like this:
```./content/xxYY/fieldnotes/lastname_firstname/xxYY_fieldnotes_lastname_firstname_file-description.html```
or
```./content/xxYY/annotations/subject_lastname1+lastname2/xxYY_annotations_subject_lastname1+lastname2_file-description.html```

Now let's do some math:
- we lose `9` characters to `content/`
- each semester folder is exactly `5` characters, e.g. `sp16/` (with the exception of `sp17dh/`)
- `fieldnotes/` is `11` characters, `annotations/` is `12`
- `.html` is `5` characters
- suppose the subfolder name is `n` characters, so `n+2` including the `_` and `/`
- we lose at most `5 + 1 + 12 + 1 + n + 2 + 1 = 22 + n` characters due to the duplication of the semester, category, subfolder, and underscores in the file name

So if we say the subfolder name is `n` characters, that only gives us `200 - 9 - 5 - 12 - 5 - n - 2 - 22 - n = 145 - 2n` characters for the actual file name. One example is the annotations project called `frame-casting+molded-roses+molded-paper_carlson+katz` in fall 2014, which is `52` characters. So that leaves `145 - 104 = 41` characters for the file name itself, and that's cutting it a little too close for comfort in my opinion.

My recommendations:
- use abbreviations for categories (`annotations -> ann`, `fieldnotes -> fld` or something similar)
- exercise maximum parsimoniousness when naming annotation folders and file names
  - they merely need be unique and basically indicative of the content, not a summary or full essay title
  - think of it like you're naming a URL!

**Comment by gschare** [comment]
annotations and fieldnotes have been shortened

**Comment by gschare** [comment]
All file names are now well under 200 characters, except for a few ones in files/

**Comment by njr2128** [comment]
Good to reference in general, but no outstanding issues to resolve
