### ISSUE TITLE
one index.html page not updated

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/fieldnotes-content#30]
In my most recent commit (https://github.com/cu-mkp/fieldnotes-content/pull/29/commits/026b506e8df7f9bd3096de8cd9fb6d6f9450e484), I ran the pandoc python script that converts the markdown indices into html versions. This should have updated all indices in fa14, but the outermost index did not update: https://github.com/cu-mkp/fieldnotes-content/blob/main/content/fa14/index.html

Any ideas why not?

**Comment by njr2128** [comment]
same thing for sp15, too: https://github.com/cu-mkp/fieldnotes-content/blob/main/content/sp15/index.html and https://github.com/cu-mkp/fieldnotes-content/commit/c7afb42b5ab026573e991a74ee7c477af60fb1ef

**Comment by gschare** [comment]
For some reason I had written `subpages` instead of `pages` for only the `semester.html` template, so it was ignoring what we had written in the .md files.

See PR #48
