### ISSUE TITLE
manual organization of files

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/fieldnotes-content#9]
given work in #8 and https://github.com/cu-mkp/fieldnotes-restructuring/issues/21 and https://github.com/cu-mkp/fieldnotes-restructuring/issues/22, each semester needs to be reviewed and the files organized into `annotations` vs. `fieldnotes` vs. `profiles`

**Comment by gschare** [comment]
Filenames in `annotations/` folders have been standardized according to the [schema](https://github.com/cu-mkp/fieldnotes-content/blob/main/naming-spec.md).

**Comment by njr2128** [comment]
I think the basic work to be completed for this task has been completed. Next steps should be logged in other open issues or in new issues to be opened
